# Generated by Django 2.1.2 on 2018-11-04 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('api', '0003_auto_20181103_2239'),
	]

	operations = [
		migrations.AlterField(
			model_name='enumfield',
			name='choices',
			field=django.contrib.postgres.fields.ArrayField(
				base_field=models.TextField(),
				size=None
			),
		),
	]
